apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: firefox-cli-2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  healthcheck:
    enabled: true
    image: us.gcr.io/dotted-forest-314903/firefox-cli-2-healthcheck:010bab54b24dc0207582282f02e084890c2722a26a9f4563ebeae49ea0cbe0a0
  image: us.gcr.io/dotted-forest-314903/firefox-cli-2-challenge:3bafc270dcf5277668ef0504574754141b57a23b7ed4207fdfccbe980939c427
