apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: uiuctf-egress-k8s-api
spec:
  podSelector:
    matchLabels:
      uiuctf-egress: k8s-api
  egress:
    - to:
        - ipBlock:
            cidr: 172.16.0.34/32
      ports:
        - protocol: TCP
          port: 443
  policyTypes:
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: uiuctf-egress-instancer-managed
spec:
  podSelector:
    matchLabels:
      uiuctf-egress: instancer-managed
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              uiuctf-namespace: instancer-managed
  policyTypes:
    - Egress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instancer-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instancer-manager-clusterroles
rules:
  - apiGroups: ["*"]
    resources:
      - namespaces
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instancer-manager
subjects:
  - kind: ServiceAccount
    name: instancer-manager
    namespace: default
roleRef:
  kind: ClusterRole
  name: instancer-manager-clusterroles
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instancer
  namespace: default
  labels:
    app: instancer
spec:
  selector:
    matchLabels:
      app: instancer
  template:
    metadata:
      labels:
        app: instancer
        uiuctf-egress: k8s-api
    spec:
      containers:
        - name: instancer
          image: us.gcr.io/dotted-forest-314903/instancer-instancer:f5cc74c84a332aee5910ed12eb93dcf3cd4015e35c23ec5e3496d76135698c37
          ports:
            - containerPort: 1337
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: instance-templates-volume
              mountPath: /etc/instance-templates
      serviceAccountName: instancer-manager
      volumes:
        - name: instance-templates-volume
          configMap:
            name: instance-templates
---
apiVersion: v1
kind: Service
metadata:
  name: instancer
  namespace: default
  labels:
    app: instancer
spec:
  selector:
    app: instancer
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostproxy
  namespace: default
  labels:
    app: hostproxy
spec:
  selector:
    matchLabels:
      app: hostproxy
  template:
    metadata:
      labels:
        app: hostproxy
        uiuctf-egress: instancer-managed
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: hostproxy
          image: us.gcr.io/dotted-forest-314903/instancer-hostproxy:7410110f09875097c6cb1a5fe85afee640fca748a1edbbb34adeb741b32cb069
          ports:
            - containerPort: 80
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
---
apiVersion: v1
kind: Service
metadata:
  name: hostproxy
  namespace: default
  labels:
    app: hostproxy
spec:
  selector:
    app: hostproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
