apiVersion: batch/v1
kind: Job
metadata:
  name: INSTANCE_NAME
  namespace: blackbox-managed
  labels:
    name: INSTANCE_NAME
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: blackbox
        name: INSTANCE_NAME
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: challenge
          image: us.gcr.io/dotted-forest-314903/blackbox-challenge:5c569640f365859dc7441b536684d8532888f899522bdcee67d83cfbbe4da1c9
          ports:
            - containerPort: 1337
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
              subPath: tmp
      restartPolicy: Never
      volumes:
        - name: tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
  ttlSecondsAfterFinished: 0
---
apiVersion: v1
kind: Service
metadata:
  name: INSTANCE_NAME
  namespace: blackbox-managed
  labels:
    name: INSTANCE_NAME
  ownerReferences: null
spec:
  selector:
    app: blackbox
    name: INSTANCE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: ClusterIP
