apiVersion: batch/v1
kind: Job
metadata:
  name: INSTANCE_NAME
  namespace: spoink-managed
  labels:
    name: INSTANCE_NAME
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: spoink
        name: INSTANCE_NAME
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      containers:
        - name: challenge
          image: us.gcr.io/dotted-forest-314903/spoink-challenge:8357c374d908c2d061011a15b0fb91138f77525be85ada920088077da1810b18
          ports:
            - containerPort: 8080
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs
              subPath: tmp
      restartPolicy: Never
      volumes:
        - name: tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
  ttlSecondsAfterFinished: 0
---
apiVersion: v1
kind: Service
metadata:
  name: INSTANCE_NAME
  namespace: spoink-managed
  labels:
    name: INSTANCE_NAME
  ownerReferences: null
spec:
  selector:
    app: spoink
    name: INSTANCE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
