apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: horse
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 1337
        targetPort: 1337
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: us.gcr.io/dotted-forest-314903/horse-healthcheck:a836d2f56f261fe8855fb617c2b3032d29e8e269f07930f42355d68e83479bb2
  image: us.gcr.io/dotted-forest-314903/horse-challenge:9eb3a1618cd73344a66421775e8c7c4f0846a1c87941e9dd97eaff2e1eda527c
